# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import adr_pb2 as adr__pb2


class ServiceDefinitionStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.adr = channel.unary_unary(
        '/adr.ServiceDefinition/adr',
        request_serializer=adr__pb2.InputString.SerializeToString,
        response_deserializer=adr__pb2.ADRReturnFloat.FromString,
        )


class ServiceDefinitionServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def adr(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServiceDefinitionServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'adr': grpc.unary_unary_rpc_method_handler(
          servicer.adr,
          request_deserializer=adr__pb2.InputString.FromString,
          response_serializer=adr__pb2.ADRReturnFloat.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'adr.ServiceDefinition', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
